fixes #21 fixed CDI issues for unit tests, there are still issues in the test, but not CDI related ones, the SQL transaction is rolled back due to integrity constraints from code I uncommented, so I'm not sure this code is valid, please check on your side.
javax.persistence.RollbackException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.7.v20200504-69f2c2b80d): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: "PUBLIC.PRIMARY_KEY_44 ON PUBLIC.HEUREDEPASSAGE(ARRET_ID, TRAIN_ID) VALUES 1"; SQL statement:
INSERT INTO HEUREDEPASSAGE (ISCREATED, PASSAGE, arret_id, train_id) VALUES (?, ?, ?, ?) [23505-199]
Error Code: 23505
Call: INSERT INTO HEUREDEPASSAGE (ISCREATED, PASSAGE, arret_id, train_id) VALUES (?, ?, ?, ?)
	bind => [false, 2020-12-24T00:43:24.146288373, 2, 1]